version: '3.8'

services:
  application-service:
    container_name: byte-burguer-api
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT=1
        - progress=plain
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - database
        # condition: service_healthy
    healthcheck:
      test: curl -X GET http://localhost:8000/healthcheck || exit 1
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 10s

  database:
    container_name: byte-burguer-mongodb
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    volumes: 
      - ./database_data:/data/db
      - ./seeds/seed.js:/docker-entrypoint-initdb.d/seed.js
    healthcheck: 
      test: echo 'db.runCommand({find:"app_db_name.devUser"}).ok' | mongosh --authenticationDatabase admin --host database -u mongoadmin -p mongopassword admin --quiet | grep -q 1
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 10s

volumes:
  mymongodata:
