version: '3.8'

services:

  application:
    container_name: byte-burguer-api
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT=1
        - progress=plain
    networks:
      - stack-network
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - database
      - localstack
    healthcheck:
      test: curl -X GET http://localhost:8000/healthcheck || exit 1
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 10s

  database:
    container_name: database-postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - stack-network
    ports:
      - "5432:5432"
    volumes:
      # - /var/lib/postgresql/data
      - ./seeds/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  migrations:
    container_name: sqlalchemy-migrations
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT=1
        - progress=plain
    networks:
      - stack-network
    env_file:
      - .env.dev
    depends_on:
      - database
    entrypoint: python3 ./migrations.py
  
  localstack:
    container_name: aws-cloud-mock
    image: localstack/localstack:latest
    networks:
      - stack-network
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      DEBUG: 0
      SERVICES: sqs
      LOCALSTACK_HOST: localhost:4566
    env_file:
      - .env.dev
    # volumes:
    #   - "./localstack_data:/var/lib/localstack"
    #   - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  stack-network:
    driver: bridge
