version: '3.7'

services:
  fast-api-service:
    container_name: byte-burguer-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
    depends_on:
      - postgres

  postgres:
    container_name: byte-burguer-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
      - ./seeds:/docker-entrypoint-initdb.d  # Montando o diretório seeds no contêiner