version: '3.7'

services:
  fast-api-service:
    container_name: fast-api-service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env-dev
      