version: '3.8'

services:
  application-service:
    container_name: byte-burguer-orders-api
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT=1
        - progress=plain
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - database
    healthcheck:
      test: curl -X GET http://localhost:8000/healthcheck || exit 1
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 10s

  database:
    container_name: byte-burguer-orders-ostgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
