apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  DATABASE_USERNAME: {{DATABASE_USERNAME}}
  DATABASE_HOST: {{DATABASE_HOST}}
  DATABASE_PORT: {{DATABASE_PORT}}
  DATABASE_NAME: {{DATABASE_NAME}}
  DATABASE_PASSWORD: {{DATABASE_PASSWORD}}