apiVersion: apps/v1
kind: Deployment
metadata:
  name: byte-burguer-api
  labels:
    app: byte-burguer-api
spec:
  template:
    metadata:
      name: byte-burguer-pod
      labels:
        app: byte-burguer-pod
    spec:
      containers:
        - name: byte-burguer-api
          image: hiltonbruno633/bytebyteburguers-fast-api-service:2.1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configmap-api
          livenessProbe:
            httpGet:
                path: /v1/pedido
                port: 8000
            periodSeconds: 10  
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health_check 
              port: 8000
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              cpu: 10m
  replicas: 3
  selector:
    matchLabels: 
      app: byte-burguer-pod

