apiVersion: apps/v1
kind: Deployment
metadata:
  name: byte-burguer-backend
  labels:
    app: byte-burguer-backend
spec:
  replicas: 1
  template:
    metadata:
      name: byte-burguer-pod
      labels:
        app: byte-burguer-pod
    spec:
      containers:
        - name: byte-burguer-backend
          image: hiltonbruno633/bytebyteburguers-fast-api-service:2.1
          ports:
            - containerPort: 8000
          envFrom:
            -   configMapRef:
                  name: configmap-backend
  selector:
    matchLabels: 
      app: byte-burguer-pod

