apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-database
spec:
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
