
APPLICATION_SETTINGS_ENVIRONMENT_VARIABLES = {
    'APPLICATION_NAME': 'tst-name',
    'APPLICATION_HOST': '0.0.0.0',
    'APPLICATION_PORT': '1234',
    'ENVIRONMENT': 'dev',
    'WORKERS': '1'
}

DATABASE_SETTINGS_ENVIRONMENT_VARIABLES = {
    'DATABASE_USERNAME': 'postgres',
    'DATABASE_PASSWORD': 'postgres',
    'DATABASE_HOST': 'localhost',
    'DATABASE_PORT': '5432',
    'DATABASE_NAME': 'postgres'
}
